@url = https://8080-eulaahsantoos-aula1309-5ahgovcijqq.ws-us116.gitpod.io

###
POST {{url}}/pessoas
Content-Type: application/json

{
    "nome": "Mike Vale",
    "idade": 18
}

###
GET {{url}}/pessoas

###
GET {{url}}/pessoas/1

###
PUT  {{url}}/pessoas/2
Content-Type: application/json

{
    "nome": "Registro Modificado",
    "idade": 25
}


###
DELETE {{url}}/pessoas/2